.data
LEVEL_HARD \
    BYTE Q_REPEAT_X + 31, (B_BLUE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_PURPLE + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_WHITE + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_WHITE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_BLUE + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_WHITE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_RED + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_WHITE + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_WHITE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_GREEN + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_BLUE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_BLUE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_RED + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_GREEN + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_GREEN + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_PURPLE + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_PURPLE + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_WHITE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_RED + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_WHITE + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_WHITE + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_GREEN + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_PURPLE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_PURPLE + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_WHITE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_RED + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_BLUE + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 19, (B_PURPLE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_WHITE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_BLUE + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_WHITE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_WHITE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_BLUE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_PURPLE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_WHITE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_RED + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_WHITE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_BLUE + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 8, (B_YELLOW + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_BLUE + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_WHITE + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_GREEN + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_PURPLE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_BLUE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_GREEN + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_WHITE + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_WHITE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_YELLOW + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_PURPLE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_RED + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_BLUE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_WHITE + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 11, (B_GREEN + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_WHITE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_BLUE + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_GREEN + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_RED + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_PURPLE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_BLUE + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_YELLOW + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_YELLOW + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_WHITE + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 13, (B_YELLOW + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_RED + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_RED + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_BLUE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_WHITE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_WHITE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_RED + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_WHITE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_WHITE + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_PURPLE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_WHITE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_RED + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_NEXT, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_WHITE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_RED + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_GREEN + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 17, (B_YELLOW + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_YELLOW + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_GREEN + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_BLUE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_PURPLE + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_BLUE + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_WHITE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_YELLOW + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_YELLOW + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_WHITE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_YELLOW + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_GREEN + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_WHITE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_PURPLE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_RED + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_WHITE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_PURPLE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_BLUE + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_WHITE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 8, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_BLUE + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_GREEN + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_RED + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_PURPLE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_WHITE + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_GREEN + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_BLUE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_GREEN + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_WHITE + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_PURPLE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_PURPLE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_RED + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_PURPLE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_BLUE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_WHITE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_RED + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_RED + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_WHITE + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_BLUE + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_PURPLE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 30, (B_RED + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_RED + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 8, (B_GREEN + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 11, (B_GREEN + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_BLUE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_RED + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_YELLOW + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_WHITE + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_PURPLE + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_YELLOW + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_NEXT, (B_YELLOW + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_PURPLE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_RED + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_GREEN + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_BLUE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_RED + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_RED + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 11, (B_BLUE + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_RED + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_WHITE + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_BLUE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_YELLOW + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_PURPLE + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_BLUE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_BLUE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_RED + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_WHITE + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_YELLOW + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_WHITE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_WHITE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_BLUE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 14, (B_YELLOW + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_YELLOW + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_BLUE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_BLUE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_BLUE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_BLUE + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_BLUE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_WHITE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_WHITE + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_WHITE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_GREEN + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_YELLOW + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_YELLOW + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_GREEN + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 11, (B_WHITE + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 11, (B_RED + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_PURPLE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 8, (B_YELLOW + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_WHITE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_WHITE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 12, (B_BLUE + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_WHITE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_WHITE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_BLUE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_WHITE + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 16, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_BLUE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_BLUE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_NEXT, (B_BLUE + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 13, (B_BLUE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_WHITE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_YELLOW + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_BLUE + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_BLUE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_BLUE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_GREEN + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 8, (B_PURPLE + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_WHITE + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_BLUE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_PURPLE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_YELLOW + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_RED + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_BLUE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 8, (B_PURPLE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_WHITE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_RED + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_BLUE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_GREEN + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_WHITE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_PURPLE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_YELLOW + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_RED + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_WHITE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_RED + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_BLUE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_GREEN + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 31, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 25, (B_YELLOW + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 8, (B_RED + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_GREEN + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_RED + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_YELLOW + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_GREEN + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_WHITE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_PURPLE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_RED + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_PURPLE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_GREEN + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_WHITE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_WHITE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_PURPLE + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_BLUE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_BLUE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_BLUE + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 15, (B_GREEN + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_YELLOW + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_WHITE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_PURPLE + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_YELLOW + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_WHITE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_WHITE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_NEXT, (B_RED + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_BLUE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_NEXT, (B_WHITE + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_PURPLE + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_BLUE + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_BLUE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_WHITE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_GREEN + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_BLUE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_RED + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_GREEN + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_RED + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_GREEN + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_YELLOW + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_GREEN + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_YELLOW + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 11, (B_WHITE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_NEXT, (B_WHITE + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 11, (B_BLUE + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_RED + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 15, (B_WHITE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_YELLOW + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_GREEN + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_WHITE + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_WHITE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_PURPLE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_GREEN + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_BLUE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_RED + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_GREEN + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_RED + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_RED + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_BLUE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_RED + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_GREEN + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_WHITE + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_BLUE + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_RED + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_GREEN + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_PURPLE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_BLUE + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_BLUE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_PURPLE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_YELLOW + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_GREEN + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_NEXT, (B_BLUE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_WHITE + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 8, (B_RED + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_BLUE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_BLUE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_YELLOW + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_YELLOW + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_GREEN + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_WHITE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_WHITE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_WHITE + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_PURPLE + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_BLUE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_BLUE + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_WHITE + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_BLUE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_GREEN + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_NEXT, (B_GREEN + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_GREEN + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_GREEN + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_BLUE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_PURPLE + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_PURPLE + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_YELLOW + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_BLUE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 8, (B_BLUE + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_GREEN + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_WHITE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_BLUE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_GREEN + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_RED + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_WHITE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_WHITE + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_BLUE + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_WHITE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_BLUE + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_RED + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 11, (B_YELLOW + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_BLUE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_RED + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_PURPLE + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_GREEN + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_YELLOW + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_YELLOW + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_BLUE + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_GREEN + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_RED + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 11, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_BLUE + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_BLUE + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 8, (B_BLUE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_RED + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_PURPLE + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_GREEN + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_GREEN + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_PURPLE + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_WHITE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_RED + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 12, (B_WHITE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_PURPLE + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_BLUE + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_WHITE + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_PURPLE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_YELLOW + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_PURPLE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 8, (B_PURPLE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_WHITE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_BLUE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_BLUE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_WHITE + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_GREEN + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_BLUE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_PURPLE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_WHITE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_WHITE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_YELLOW + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_BLUE + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_RED + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_WHITE + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_BLUE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_PURPLE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_YELLOW + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_YELLOW + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_PURPLE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_WHITE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_YELLOW + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), (B_WHITE + LEN_B_COLORS * 1), (B_PURPLE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_RED + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_BLUE + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_PURPLE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_RED + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_BLUE + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_PURPLE + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_RED + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_BLUE + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_PURPLE + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_BLUE + LEN_B_COLORS * 0), (B_PURPLE + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_WHITE + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_GREEN + LEN_B_COLORS * 0), (B_BLUE + LEN_B_COLORS * 1), (B_WHITE + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_BLUE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 1, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 21, (B_PURPLE + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_EOG