.data
LEVEL_NORMAL \
    BYTE Q_REPEAT_X + 20, (B_GREEN + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 21, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 20, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 17, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 6, Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 22, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 21, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 15, (B_RED + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 11, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 9, Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_YELLOW + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 6, Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_RED + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_YELLOW + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, Q_NEXT
    BYTE Q_REPEAT_X + 9, Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 10, Q_NEXT
    BYTE Q_REPEAT_X + 3, Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_YELLOW + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, Q_NEXT
    BYTE Q_REPEAT_X + 5, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 11, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 3, Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 8, Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 11, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_YELLOW + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 11, Q_NEXT
    BYTE Q_REPEAT_X + 3, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 9, Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_YELLOW + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_YELLOW + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 15, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 11, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 16, Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 8, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 6, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 9, Q_NEXT
    BYTE Q_REPEAT_X + 11, Q_NEXT
    BYTE Q_REPEAT_X + 10, Q_NEXT
    BYTE Q_REPEAT_X + 3, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 5, Q_NEXT
    BYTE Q_REPEAT_X + 10, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_GREEN + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_GREEN + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 16, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_GREEN + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 9, Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_YELLOW + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 5, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 6, Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 6, Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 9, Q_NEXT
    BYTE Q_REPEAT_X + 11, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 9, Q_NEXT
    BYTE Q_REPEAT_X + 11, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 5, Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_GREEN + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 11, Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 3, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 5, Q_NEXT
    BYTE Q_REPEAT_X + 5, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 16, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 20, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 20, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 19, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_RED + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 5, Q_NEXT
    BYTE Q_REPEAT_X + 20, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 21, Q_NEXT
    BYTE Q_REPEAT_X + 17, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 15, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, Q_NEXT
    BYTE Q_REPEAT_X + 9, Q_NEXT
    BYTE Q_REPEAT_X + 11, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 5, Q_NEXT
    BYTE Q_REPEAT_X + 3, Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_YELLOW + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 15, (B_YELLOW + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, Q_NEXT
    BYTE Q_REPEAT_X + 10, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, Q_NEXT
    BYTE Q_REPEAT_X + 10, Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_YELLOW + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_RED + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_GREEN + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_YELLOW + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 10, Q_NEXT
    BYTE Q_REPEAT_X + 10, Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 3, Q_NEXT
    BYTE Q_REPEAT_X + 5, Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 8, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_GREEN + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 5, Q_NEXT
    BYTE Q_REPEAT_X + 6, Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_GREEN + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 11, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_YELLOW + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 6, Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_YELLOW + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 2, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 3, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 10, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 6, Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 11, Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 11, Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_RED + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_YELLOW + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 15, (B_YELLOW + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, Q_NEXT
    BYTE Q_REPEAT_X + 11, Q_NEXT
    BYTE Q_REPEAT_X + 9, Q_NEXT
    BYTE Q_REPEAT_X + 10, Q_NEXT
    BYTE Q_REPEAT_X + 10, Q_NEXT
    BYTE Q_REPEAT_X + 5, Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_RED + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 6, Q_NEXT
    BYTE Q_REPEAT_X + 6, Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_YELLOW + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 5, Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 5, Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 10, Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 6, Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 6, Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 11, (B_YELLOW + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 5, Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 8, Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, Q_NEXT
    BYTE Q_REPEAT_X + 11, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_YELLOW + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 11, (B_RED + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 9, Q_NEXT
    BYTE Q_REPEAT_X + 10, Q_NEXT
    BYTE Q_REPEAT_X + 5, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 6, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 8, Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 3, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 3, Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 3, Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 14, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 5, Q_NEXT
    BYTE Q_REPEAT_X + 22, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 22, Q_NEXT
    BYTE Q_REPEAT_X + 17, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_GREEN + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 22, (B_YELLOW + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 21, Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 11, Q_NEXT
    BYTE Q_REPEAT_X + 11, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 8, Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 11, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_GREEN + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 11, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_RED + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 8, Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 3, Q_NEXT
    BYTE Q_REPEAT_X + 10, Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 8, Q_NEXT
    BYTE Q_REPEAT_X + 6, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 10, Q_NEXT
    BYTE Q_REPEAT_X + 10, Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_YELLOW + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 8, (B_YELLOW + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_RED + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 10, Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 11, Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 12, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 2, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 8, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 9, Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_YELLOW + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 11, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 8, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 6, Q_NEXT
    BYTE Q_REPEAT_X + 6, Q_NEXT
    BYTE Q_REPEAT_X + 5, Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 3, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 14, Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 6, Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_RED + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_YELLOW + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 9, Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_RED + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 6, Q_NEXT
    BYTE Q_REPEAT_X + 5, Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 6, Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 12, Q_NEXT
    BYTE Q_REPEAT_X + 8, (B_GREEN + LEN_B_COLORS * 1), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_YELLOW + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 6, (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 8, (B_RED + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 8, Q_NEXT
    BYTE Q_REPEAT_X + 11, Q_NEXT
    BYTE Q_REPEAT_X + 9, (B_GREEN + LEN_B_COLORS * 1), (B_RED + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 5, (B_GREEN + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 3, (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_GREEN + LEN_B_COLORS * 0), (B_RED + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_REPEAT_X + 4, Q_NEXT
    BYTE Q_REPEAT_X + 7, Q_NEXT
    BYTE Q_REPEAT_X + 7, (B_GREEN + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_YELLOW + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_RED + LEN_B_COLORS * 0), (B_GREEN + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 10, (B_YELLOW + LEN_B_COLORS * 1), (B_YELLOW + LEN_B_COLORS * 2), Q_NEXT
    BYTE Q_REPEAT_X + 4, (B_RED + LEN_B_COLORS * 0), Q_NEXT
    BYTE Q_REPEAT_X + 30, Q_NEXT
    BYTE Q_REPEAT_X + 88, (B_YELLOW + LEN_B_COLORS * 0), (B_YELLOW + LEN_B_COLORS * 1), Q_NEXT
    BYTE Q_EOG